### PR TITLE
add whatsapp

### PR DESCRIPTION
**Pull request by prdm0**
Add whatsapp social.

### CODE REVIEW

**Comment by budparr** [comment]
Thank you. I think the only thing we need to review is the svg file

**Comment by prdm0** [comment]
Add in social-shere.html:

```html
     {{ $whatsapp_href := printf "https://api.whatsapp.com/send?text=%s&url=%s" $url}}
    <a href="{{ $whatsapp_href }}" class="whatsapp no-underline" aria-label="share on Whatsapp">
      {{ partialCached "svg/whatsapp.svg" (dict "size" $icon_size) $icon_size }}
    </a>
```

**Comment by prdm0** [comment]
See how it will look [here](https://prdm0.rbind.io/post/workshop-paraibano-de-estat%C3%ADstica-2020/).

Kind regards.

**Comment by prdm0** [comment]
Hello, can the share option on whatsapp be reviewed?

**Comment by regisphilibert** [comment]
Hi @prdm0 I recently merged #422 which refactors the way socials are handled on the site. It makes it very easy for users to add social services on their project even if it's not built in ananke. You can read more about it here: https://github.com/theNewDynamic/gohugo-theme-ananke#social-follow--share

If want you can submit a new PR. All you have to do is 
1. add your service to: [func/socials/GetBuiltInServicesDefaults](https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/partials/func/socials/GetBuiltInServicesDefaults.html)
2. Add the icon (name must match key from above) to `assets/ananke/socials/`

**Pull request closed without merging**
