### PR TITLE
Add Strava social icon

### PR DESCRIPTION
**Pull request by danielcorin**
[Strava](https://www.strava.com/) is a social app for athletes for logging and tracking workouts. I've added a preview of the new icon and mouse over color below.

### CODE REVIEW

**Comment by Toparvion** [comment]
Hi @danielcorin !
Can you please explain why this PR was closed without merging into the master?
(I'd like to use Strava icon on my site)

**Comment by danielcorin** [comment]
> Hi @danielcorin !
> Can you please explain why this PR was closed without merging into the master?
> (I'd like to use Strava icon on my site)

The PR wasn't accepted for a while so I closed this due to staleness, but I'm happy to reopen

**Comment by danielcorin** [comment]
@Toparvion, it appears a little work will needed to get this into shape so it can merge. I'll try to get to it this weekend, but feel free to take over if you'd like

**Comment by Toparvion** [comment]
Hi @danielcorin! Thank you for reopening the PR! 
> I'll try to get to it this weekend, but feel free to take over if you'd like

I would be glad to help but due to current scheduling I'm not sure about when I'll be able to do it. Hope this will change soon.

**Comment by danielcorin** [comment]
@Toparvion, no worries. I took a pass today I believe this currently is in (or is close) to a state where it can be merged

**Comment by regisphilibert** [comment]
Hi @danielcorin. Sorry for having been this long, but I recently merged #422 which refactors the way socials are handled on the site. It makes it very easy for users to add social services on their project even if it's not built in ananke. You can read more about it here: https://github.com/theNewDynamic/gohugo-theme-ananke#social-follow--share

If want you can submit a new PR. All you have to do is 
1. add your service to: [func/socials/GetBuiltInServicesDefaults](https://github.com/theNewDynamic/gohugo-theme-ananke/blob/master/layouts/partials/func/socials/GetBuiltInServicesDefaults.html)
2. Add the icon (name must match key from above) to `assets/ananke/socials/`

**Pull request closed without merging**
