### PR TITLE
Remove scrollbars unless needed

### PR DESCRIPTION
**Pull request by gerrywastaken**
Ananke has a very minimal design but code sections were including
horizontal and vertical scrollbars even when there is only a single line
of code. I feel that removing them unless necessary leads to a less
cluttered look with no downsides.

### CODE REVIEW

**Comment by gerrywastaken** [comment]
I understand this is a personal preference, but I thought I'd make a PR just in case you agreed.

**Comment by regisphilibert** [comment]
Hi @gerrywastaken, I'm going to have to ask you to process the css for me. 
1. Sync upstream/master and merge into your PR
2. `cd src`, `npm install`,  `npm run build:production`
3. Commit the 3 changed files.

Thanks a ton!

**Comment by gerrywastaken** [comment]
@regisphilibert Thanks for simple instructions :) I've included the production build as requested. Please let me know if there is anything else needed.

**Comment by gerrywastaken** [comment]
@regisphilibert I believe I've updated it with the changes you requested.

**Comment by regisphilibert** [comment]
Hi @gerrywastaken sorry for taking so long. I was waiting for a major style upgrade (which got rid of webpack altogether) and failed to go back to this.

Looking back at it I'm failing to see the scrollbar on my browser (with a one-line block)

Shall you have the time could you double check this is still a problem on the latest [version](https://github.com/theNewDynamic/gohugo-theme-ananke/releases/tag/v2.8.1) of Ananke?

**Comment by gerrywastaken** [comment]
@regisphilibert no worries at all. I'm grateful you responded. However, if you can't see it, then it's likely fixed. I also notice that the style is no longer there so we couldn't apply this change anyway. Happy to close and thanks for your continued work on this theme. :)

**Pull request closed without merging**
